### ISSUE TITLE
Initial tests

### ISSUE THREAD

**Issue by kannab98** [StSav012/e-502#1]
Добрый день!

Попробовал запустить программу с конфигами из репозитория. Возникло несколько вопросов. 
Запускал с несколькими версиями интерпретаторов под Arch Linux: 
* v. 3.10.5 в виртуальном окружении с минимальным колличеством зависимостей
Получил следующую ошибку от `pyqtgraph`
```
Traceback (most recent call last):
  File "/home/ponur/e-502/venv/lib/python3.10/site-packages/pyqtgraph/widgets/SpinBox.py", line 583, in paintEvent
    self._updateHeight()
  File "/home/ponur/e-502/venv/lib/python3.10/site-packages/pyqtgraph/widgets/SpinBox.py", line 575, in _updateHeight
    self.setMaximumHeight(1e6)
TypeError: setMaximumHeight(self, int): argument 1 has unexpected type 'float'
```

* На anaconda v. 3.8.8 удалось запуститься. 
## Незначительный баг
В файле `stubs.py`  На версии sys (3,8,8)  не обработались исключения и выдавалась ошибка на импорт NoneType. Пока что создал вот такой "костыль" :
```
#if sys.version_info >= (3, 10):
#    from typing import NoneType
#else:
NoneType = type(None)
```
## Баг или неправильный запуск программы?
При запуске с конфигом 

```
[General]
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x62\0\0\0\xd7\0\0\x3\xf3\0\0\x3S\0\0\x2\x62\0\0\0\xd7\0\0\x3\xf3\0\0\x3S\0\0\0\0\0\0\0\0\x5\0\0\0\x2\x62\0\0\0\xd7\0\0\x3\xf3\0\0\x3S)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x1\x92\0\0\x2}\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[channelSettings]
1\channel=1
1\enabled=true
2\averaging=2
2\channel=3
2\enabled=true
2\mode=3
size=2

[digitalLines]
1\pushed=true
2\pushed=false
3\pushed=false
4\pushed=false
5\pushed=true
6\pushed=true
7\pushed=false
8\pushed=false
size=8

[parameters]
frequencyDivider=5
ipAddress=169.254.79.177
measurementDuration=10
sampleRate=0.5
samplesPortionSize=1000
savingLocation=/home/ponur/e-502/data
```
При начале записи возникает ошибка индексирования

```
Traceback (most recent call last):
  File "/home/ponur/e-502/gui/app.py", line 64, in on_button_start_clicked
    while any(self._saving_location(i + 1).exists() for i in range(32)):
  File "/home/ponur/e-502/gui/app.py", line 64, in <genexpr>
    while any(self._saving_location(i + 1).exists() for i in range(32)):
  File "/home/ponur/e-502/gui/app.py", line 48, in _saving_location
    / self.tabs[channel].title()
IndexError: list index out of range
```

Поскольку функция отвечала только за имя файла, куда после сохранялись данные, временно поменял `self.tabs[channel].title()` на `self.tabs[0].title()`. 

Получил следующий output в файл `imp_000001.csv`:
```
-4.0549963926831916e+31
-4.055058289685156e+31
-4.0549654441822095e+31
-4.0549654441822095e+31
-4.0549963926831916e+31
-4.0549654441822095e+31
-4.0550273411841738e+31
-4.055058289685156e+31
-4.0549654441822095e+31
-4.0550273411841738e+31
-4.055058289685156e+31
```

**Comment by StSav012** [comment]
Please reveal the output of `pip freeze`.

**Comment by StSav012** [comment]
As for the `pyqtgraph` error, I won't fix it. Make an issue on [their side](https://github.com/pyqtgraph/pyqtgraph).

The error in `stubs.py` looks bizarre. However, as I don't use `NoneType` anywhere, here is the fix: https://github.com/StSav012/e-502/commit/7c7a1d74eee1c505ceced5bfb454d57dac32b9ad.

The `IndexError` looks like it should have been fixed long ago. I'll check whether the code here is the latest I possess. As a short fix, consider https://github.com/StSav012/e-502/commit/c10ed3bdd45e99895192653b41e6361b6d26c940.

Finally, the input data look anything but wrong. I wonder if the byte order is right. I have `sys.byteorder == 'little'` on all my systems. What is yours? Unless it's about the byte order, I need the traffic dump or any kind of connection to the device.

I've tried some manipulations. When I change the byte order, I get some -2.14e-38 to 2.14e-38 from the values you've written. This doesn't look right, either. *puzzled*

**Comment by kannab98** [comment]
Thanks for the hotfixes!

I think we should try running the scripts on the same machine.
I can provide you Wireguard tunnel to the Raspberry Pi with an E-502 connected to it. 

Will this be enough for testing?

**Comment by StSav012** [comment]
Thanks, I do suppose it is enough. Please PM me with further info.

**Comment by kannab98** [comment]
Okay, I'll give you the details on Monday. Unfortunately, I don't have access to the device right now.
